kind = "mobile"
previewPath = "/"
title = "rydnex"
version = "1.0.0"
id = "artifacts/rydnex"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25760

[services.development]
run = "pnpm --filter @workspace/rydnex run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rydnex", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/rydnex", "run", "serve" ]

[services.env]
PORT = "25760"
BASE_PATH = "/"
